### ISSUE TITLE
Sixel?

### ISSUE THREAD

**Issue by hackerb9** [csdvrx/sixel-testsuite#1]
Hi! I like this repository as it is a collection of many of the handy scripts and text files with which I like to test terminals. The one thing that confuses me is why it is called "sixel-testsuite". I had been hoping for more sixel tests, but it is almost all ANSI color and UNICODE tests. Perhaps a better name would be "ansicolor-testsuite"?

**Comment by csdvrx** [comment]
My apologies for any delay - I'm only catching this 2 years later!

You're right, I should have more tests for sixels!

This is named sixel-testsuite because I wanted to test for sixels when moving to Linux, but I had so many issues with basic ANSI and UNICODE tests failing in terminals that I focused first on these 2 subproblems.

In general, if  UNICODE and ANSI both work (including the more obscure sequences like the toggles for italics, underline...) sixels are more likely to work: these 3 problems are unrelated, but if the basics can't be done correctly, odds are sixels can't be done correctly either!

BTW another simple test is for double width support:  try `echo -e 'Hello \033#6World'`: on linux, I've only had success with xterm and wezterm.
